django/dci-union-fromDisco/banking/urls.py
from django.urls import path
from . import views

app_name = "banking"
urlpatterns = [
    path("", views.SendMoneyView.as_view(), name="send_money"),
    path("post-transaction/<data>", views.PostTransactionView.as_view(), name="post_transaction")
]

django/dci-union-fromDisco/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("banking.urls"))
]

django/dci-union-fromDisco/banking/models.py
from django.db import models

# Create your models here.

django/dci-union-fromDisco/banking/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from .helpers import get_country_names_currs

class SendMoneyForm(forms.Form):
    from_country = forms.ChoiceField(choices=get_country_names_currs())
    to_country = forms.ChoiceField(choices=get_country_names_currs())
    amount_from = forms.IntegerField(label="Send Amount")
    amount_to = forms.IntegerField(label="Reciever gets", required=False, disabled=True)

django/dci-union-fromDisco/banking/views.py
# import python modules 
from decimal import Decimal
from urllib import parse

# import django modules
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView
from django.urls import reverse, reverse_lazy
# import external modules
from forex_python.converter import CurrencyRates

# import app/project modules
from .forms import SendMoneyForm
from .helpers import get_country_name, get_country_names_currs


class SendMoneyView(FormView):
    template_name = "banking/transaction.html"
    success_template = "banking/post-transaction.html"
    form_class = SendMoneyForm

    
    def post(self, request, *args, **kwargs):
        """
        Convert form sender currency to reciever currency
        """
        request_object = request.POST
        from_country_curr = request_object.get("from_country")
        to_country_curr = request_object.get("to_country")
        # get amount of transfered money
        amount_from = request_object.get("amount_from")

        # Form responses are country currencies. 
        # Get the matching country name for the currency
        # with the actual code its not possible to get the country name
        # because only the currency is send. 
        # And, e.g. the EUR is currency in multiple countries
        # so its not possible to get the country by a given currency
        ##########################################################
        # from_country_name = get_country_name(from_country_curr)
        # to_country_name = get_country_name(to_country_curr)

        currency = CurrencyRates(force_decimal=True)
        # convert the incoming amount to the currency of recievers country
        try:
            converted = currency.convert(from_country_curr, to_country_curr, Decimal(amount_from))
        except:
            converted = "Something went wrong"

        context = {
            "converted": round(converted, 2),
            "amount": amount_from,
            "from_country_curr": from_country_curr,
            "to_country_curr": to_country_curr,
        }

        # with an logged in user the data would be stored in a session variable,
        # that could be called from the recieving function
        # request.session["converted"] = converted
        endcoded = parse.urlencode(context)
        return redirect("banking:post_transaction", data=endcoded)

    
class PostTransactionView(TemplateView):
    template_name = "banking/post-transaction.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["data"] = parse.parse_qs(kwargs.get("data"))
        return context
    

django/dci-union-fromDisco/banking/templates/banking/post-transaction.html
{% extends 'base.html' %}
{% block contentheader %}
<h1>Money was send:</h1>
{% endblock contentheader %}
{% block contentmain %}
<p>
    Send: {{ data.amount.0 }} {{ data.from_country_curr.0 }}
</p>
<p>
    Recieved: {{ data.converted.0 }} {{ data.to_country_curr.0 }}
</p>
{% endblock contentmain %}

django/dci-union-fromDisco/banking/templates/banking/transaction.html
{% extends 'base.html' %}
{% block contentmain %}
<p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Send</button>
    </form>
</p>
{% endblock contentmain %}

django/dci-union-fromDisco/common/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <header class="mainheader">
            <nav>
                <a href="{% url "banking:send_money" %}">Make transaction</a>
            </nav>
        </header>
        <main>
        {% block contentheader %}
            <h1>Make a Transaction</h1>
            <p>1. Choose the Country from where you want to transfer</p>
            <p>2. Choose the Country you want to transfert to.</p>
        {% endblock contentheader %}
        {% block contentmain %}{% endblock contentmain %}
        </main>
        <footer>
            {% now "F j, Y" %}
            <nav>
                <a href="http://">Imprint</a>
                <a href="http://">About</a>
                <a href="http://">Contact</a>
            </nav>
        </footer>
    </div>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>