django/python-django-urls_and_routing-fromDisco/myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("json/", views.ReturnJson.as_view(), name="return-json"),
    path("base/", views.base_view, name="base"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("cities-list/", views.CitiesListView.as_view(), name="cities-list"),
    path(
        "city-detail/<int:geonameid>",
        views.CityDetailView.as_view(),
        name="city-detail",
    ),
]

django/python-django-urls_and_routing-fromDisco/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("myapp/", include("myapp.urls")),
]

django/python-django-urls_and_routing-fromDisco/myapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Weather(models.Model):
    location = models.CharField(max_length=100)
    weather = models.CharField(max_length=100)
    date = models.DateField(default=timezone.now)

    def save(self, *args, **kwargs):
        if self._state.adding is True:
            self.date = timezone.now()
        return super(Weather, self).save(*args, **kwargs)

django/python-django-urls_and_routing-fromDisco/myapp/forms.py
from django import forms

from .models import Weather


class DateInput(forms.DateInput):
    input_type = "date"


class WeatherForm(forms.ModelForm):
    class Meta:
        model = Weather
        fields = "__all__"

        widgets = {
            "date": forms.DateInput(attrs={"type": "date"}),
        }

django/python-django-urls_and_routing-fromDisco/myapp/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView, FormView, ListView
from django.http import HttpResponse, JsonResponse
import requests
import json

# Create your views here.
from .forms import WeatherForm
from .models import Weather
from .helpers import api_call


class Index(View):
    def get(self, request):
        return HttpResponse("<h1>This is the index page</h1>")


class ReturnJson(View):
    def get(self, request):
        return JsonResponse({"This is": "the JsonResponse"})


def base_view(request):
    return render(request, "myapp/base.html")


class AboutView(TemplateView):
    template_name = "myapp/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contents"] = [
            {"title": "Its raining", "text": "Nature needs to drink, too."},
            {
                "title": "TemplateView",
                "text": "This page is rendered by a TemplateView",
            },
        ]
        return context


class WeatherFormAddView(FormView):
    model = Weather
    form_class = WeatherForm
    template_name = "myapp/weather-add.html"
    success_url = "/myapp/weather-listing"

    def form_valid(self, form):
        if form.is_valid():
            form.save()
        return super().form_valid(form)


# class WeatherListView(ListView):
#     model = Weather
#     context_object_name = "weather_listing"
#     template_name = "myapp/cities-list.html"


class CitiesListView(TemplateView):
    template_name = "myapp/cities-list.html"
    paginate_by = 20
    context_object_name = "cities_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # define api parameters
        url = "https://countries-cities.p.rapidapi.com/location/country/DE/city/list"
        querystring = {"per_page": "20"}
        api_host = "countries-cities.p.rapidapi.com"

        # call helpers.api_call. Get back json
        cities_list_response = api_call(url, api_host, querystring)
        # context["cities_list"] = cities_list_response
        context["cities_list"] = cities_list_response

        return context

class CityDetailView(TemplateView):
    template_name = "myapp/city-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # define api parameters for city details
        url = f"https://countries-cities.p.rapidapi.com/location/city/{kwargs.get('geonameid')}"
        api_host = "countries-cities.p.rapidapi.com"
        # call helpers.api_call. Get back json
        city_detail_response = api_call(url, api_host)

        # define api parameters for city weather
        # lat and lang are required.
        lat = city_detail_response.get("latitude")
        lang = city_detail_response.get("longitude")
        url = f"https://dark-sky.p.rapidapi.com/{lat},{lang}"
        querystring = {"lang": "en", "units": "auto"}
        api_host = "dark-sky.p.rapidapi.com"
        # call helpers.api_call. Get back json
        city_weather_response = api_call(url, api_host, querystring)

        context["city_data"] = city_detail_response
        context["city_weather"] = city_weather_response
        return context

django/python-django-urls_and_routing-fromDisco/myapp/templates/myapp/about.html
{% extends "myapp/base.html" %}

{% block content %}
    {% for content in contents %}
        <div class="content">
            <h2>{{ content.title }}</h2>
            <p>{{ content.text }}</p>
        </div>
    {% endfor%}
{% endblock content %}

django/python-django-urls_and_routing-fromDisco/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="maincontent">
        <div class="header">
            <h1>Welcome to a simple Django Test</h1>
            <p>Today is {% now "SHORT_DATETIME_FORMAT" %} </p>
        </div>
        {% block content %}
        {% endblock content %}

        <div class="footer">
            <h3>Links: </h3>
            <p>
                <a href="{% url "myapp:base" %}">Base</a>
                {% if "base" in request.path %} <- Already here.{% endif %} 
            </p>
            <p>
                <a href="{% url "myapp:about" %}">About</a>
                {% if "about" in request.path %} <- Already here.{% endif %} 
            </p>
        </div>
    </div>
</body>
</html>

django/python-django-urls_and_routing-fromDisco/myapp/templates/myapp/cities-list.html
{% extends "myapp/base.html" %}

{% block content %}

    <hr>
    <h2>City details</h2>
    {% for city in cities_list.cities %}
        <div>
            
            <a href="{% url "myapp:city-detail" city.geonameid %}">
                {{ city.name }}
            </a>
            <p>
                Longitude: {{ city.longitude }}
            </p>
            <p>
                Latitude: {{ city.latitude }}
            </p>
        </div>
    {% endfor %}

    <div class="nav">
        <a href="{{ cities_list.links.first }}">Link</a>
        <p></p>
    </div>
{% endblock content %}

django/python-django-urls_and_routing-fromDisco/myapp/templates/myapp/city-detail.html
{% extends "myapp/base.html" %}

{% block content %}
    <h2>City Details</h2>
    {% for key, val in city_data.items %}
        <p>{{ key }}: {{ val }}</p>
    {% endfor %}
    <h2>City weather</h2>
    {% for key, val in city_weather.items %}
        <p>
            {{ key }}: {{ val }}
        </p>
    {% endfor %}
{% endblock content%}

django/python-django-urls_and_routing-fromDisco/myapp/templates/myapp/weather-add.html
{% extends "myapp/base.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Send</button>
    </form>
{% endblock content %}

django/python-django-urls_and_routing-fromDisco/myapp/templates/myapp/weather-listing.html
{% extends "myapp/base.html" %}

{% block content %}
    {% for weather in weather_listing %}
        <div class="weather">
            <h3>{{ weather.location }}</h3>
            <p>{{ weather.weather }}</p>
            <p>{{ weather.date }}</p>
        </div>
    {% endfor %}
{% endblock content %}