django/python-basics-django-views-and-templates-fromDisco/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from notes.views import redirect_to_note_detail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="base.html"), name="root"),
    path('<int:note_id>/', redirect_to_note_detail),
    path('notes/', include("notes.urls", namespace="notes")),
    path('todo/', include("todo.urls", namespace="todo")),
]

django/python-basics-django-views-and-templates-fromDisco/notes/urls.py
"""Notes URL Configuration."""
from django.urls import path

from notes import views

app_name = "notes"
urlpatterns = [
    path('', views.home, name="home"),
    path('sections/', views.SectionsListView.as_view(), name="sections"),
    # path('sections/', views.sections, name="sections"),
    path('sections/<section_name>/', views.BySectionView.as_view(), name="by_section"),
    path('<int:note_id>/', views.details, name="details"),
    path('<str:search_term>/', views.search, name="search"),
]

django/python-basics-django-views-and-templates-fromDisco/todo/urls.py
"""ToDo URL Configuration."""
from django.urls import path

from todo.views import details

app_name = "todo"
urlpatterns = [
    path('<int:todo_id>/', details, name="details"),
]

django/python-basics-django-views-and-templates-fromDisco/common/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <header class="mainheader">
            <nav>
                <a href="{% url 'root' %}">Home</a>
                <a href="{% url 'notes:home' %}">Notes</a>
                <a href="">Todo</a>
            </nav>
        </header>
        <main>
        {% block contentheader %}
            <h1>Welcome to the homepage</h1>
            <p>Above you can find the navigation. Feel free to click</p>
        {% endblock contentheader %}
        {% block contentmain %}{% endblock contentmain %}
        </main>
        <footer>
            {% now "F j, Y" %}
            <nav>
                <a href="http://">Imprint</a>
                <a href="http://">About</a>
                <a href="http://">Contact</a>
            </nav>
        </footer>
    </div>
</body>
</html>

django/python-basics-django-views-and-templates-fromDisco/common/templates/navlist.html
<div class="navlist">
    <ol>
    {% for el in response.nav.values %}
        {% if el.args %}
            <li><a href="{% url el.link el.args %}">{{ el.text }}</a></li>
        {% else %}
            <li><a href="{% url el.link %}">{{ el.text }}</a></li>
        {% endif %}
    {% endfor %}
    </ol>
</div>